// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7Zh-mkxz2GlK0pp3CJHT2Z2_AUBnchwE',
    appId: '1:756555297136:web:cba4ad516d46311c4d1fb5',
    messagingSenderId: '756555297136',
    projectId: 'skripsi-rice-app',
    authDomain: 'skripsi-rice-app.firebaseapp.com',
    storageBucket: 'skripsi-rice-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGySl3pxAlAfhSVOGaWHsgyghb-FQMFXs',
    appId: '1:756555297136:android:7961898a4829e4c74d1fb5',
    messagingSenderId: '756555297136',
    projectId: 'skripsi-rice-app',
    storageBucket: 'skripsi-rice-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7Q7SF7ZXIk7kFTWfpxbQz1ur3ofuhKvY',
    appId: '1:756555297136:ios:32c4333f0c5798eb4d1fb5',
    messagingSenderId: '756555297136',
    projectId: 'skripsi-rice-app',
    storageBucket: 'skripsi-rice-app.firebasestorage.app',
    iosBundleId: 'com.example.riceDiseaseApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7Q7SF7ZXIk7kFTWfpxbQz1ur3ofuhKvY',
    appId: '1:756555297136:ios:32c4333f0c5798eb4d1fb5',
    messagingSenderId: '756555297136',
    projectId: 'skripsi-rice-app',
    storageBucket: 'skripsi-rice-app.firebasestorage.app',
    iosBundleId: 'com.example.riceDiseaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7Zh-mkxz2GlK0pp3CJHT2Z2_AUBnchwE',
    appId: '1:756555297136:web:068a429940c2a1ed4d1fb5',
    messagingSenderId: '756555297136',
    projectId: 'skripsi-rice-app',
    authDomain: 'skripsi-rice-app.firebaseapp.com',
    storageBucket: 'skripsi-rice-app.firebasestorage.app',
  );
}
